### PR TITLE
Working version!

### PR DESCRIPTION
**Pull request by greg-finley**
It looks like you'll want these commits to hit the proper sbt path, skip some outdated stuff, and start redis.

However, it's still not working. I think next we'll want to install Java and Scala using sdkman: [reference](https://www.scala-sbt.org/1.x/docs/Installing-sbt-on-Linux.html) and [in progress commit that doesn't work yet](https://github.com/greg-finley-ck/lichocker/commit/48a06b4bcf6fc3fc89000a7e28235027a45e3e61).

I also hit an issue both with running Lichess in the cloud and directly on my local Mac. I am asking for help in #development channel on Discord. If you're curious here is [my gist](https://gist.github.com/greg-finley-ck/5a62e10bf2ef516ff8a8668d7777ec90) on running Lichess in the cloud; definitely some overlap with your project.

### CODE REVIEW

**Review by BrandonE — CHANGES_REQUESTED** [review]
These changes look reasonable. Please let me know when this PR is in a working state. Also, if possible, please merge [this branch](https://github.com/BrandonE/lichocker/tree/updates/oct-2019) into your changes as I believe these enhancements are also steps in the right direction.

**Comment by greg-finley** [comment]
Thanks @BrandonE ! I started my work from your `oct-2019` branch and this PR is asking to merge into that same branch. I'll see if I can get it fully working.

**Comment by BrandonE** [comment]
Ahh, I missed that detail. Once this is working, I'll merge this PR and then open a PR to merge `oct-2019` into master.

**Comment by greg-finley** [comment]
Sounds good 👍

**Comment by greg-finley** [comment]
I had played around with getting Lichess running on an Ubuntu VM in Google Cloud and applied my learnings to your Docker code. https://gist.github.com/greg-finley/5a62e10bf2ef516ff8a8668d7777ec90

This is a working version. One potential issue is that it couples together `lila` and `lila-ws`, running the latter in the background. I'm sure there is a better way. What do you recommend? Two Dockerfiles, with a docker-compose file? Then we'd ask users to run two Docker containers?

**Comment by BrandonE** [comment]
Great work @greg-finley-ck !

**Pull request merged**
